bambulab/BambuStudio

src/slic3r/GUI/DeviceManager.cpp
src/slic3r/GUI/DeviceManager.hpp
src/slic3r/GUI/Plater.cpp
src/slic3r/GUI/SelectMachine.cpp
src/slic3r/GUI/SelectMachine.hpp

Change-Id: I30a4702424fd0df2ad118505c62b6843968465da

ENH: compatible with U0 firmware

---

src/slic3r/GUI/AmsMappingPopup.cpp
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/SelectMachine.cpp

Change-Id: I4816365a2857e3e40c805af0e94654a8684c155c

FIX:fixed amsmapping button can not get click event on macos

---

src/slic3r/GUI/GUI_App.cpp

Change-Id: Iaba8184eb84ac3f16d371ef54ae169acfd13393a

set the default languange to wxLANGUAGE_ENGLISH_UK if not available

---

src/slic3r/GUI/GUI_App.cpp

Change-Id: I03fb37dc4d28bb354c7711afde6d8fb389daa53f

FIX: set the default language to local if supported

---

src/slic3r/GUI/GUI_App.cpp

Change-Id: I9286173303225330b3052d8b7a5119b046c44754

FIX: fix the hang issue after change language under macos

---

src/slic3r/GUI/Jobs/ArrangeJob.cpp
src/slic3r/GUI/Jobs/ArrangeJob.hpp

Jira: STUDIO-305
Change-Id: Ib13ccf4037cd1144177935c1184eaf203aa0eb7f

FIX: auto arranging has stauts report

---

resources/profiles/BBL.json
resources/profiles/BBL/filament/Bambu PC @BBL X1C 0.8 nozzle.json
resources/profiles/BBL/filament/Bambu TPU 95A @base.json

1 change bambu PC and TPU temperature by pineapple
Signed-off-by: salt.wei <salt.wei@bambulab.com>
Change-Id: Id2bc603893ce9e2c33f15de420c79b94cd6dd89a

ENH: some preset change

---

BuildLinux.sh

for linux building
patch picked from deftdawg, thanks deftdawg
Change-Id: I0049131fccffb3e018834f9613b10c57dcfd13e5

add extra-cmake-modules required in buildlinux.sh

---

BuildLinux.sh
Containerfile
src/platform/unix/BuildLinuxImage.sh.in

- Building improvements for building speed with Podman on Linux
- Build with Release flag so Linux network plugin is found
- AppImage changes to AppRun to workaround various segfaults
Related to #12

Improvements to building and packaging for Linux

---

bbl/i18n/es/BambuStudio_es.po

Updated Spanish translation

---

.github/ISSUE_TEMPLATE/bug_report.yml

Change-Id: I3e7b0fddd313205dd2f1b291e75bf320b6f5617b

ENH: add label when reporting a bug

---

.github/ISSUE_TEMPLATE/bug_report.yml

Change-Id: Ic92681b88cd3e96aba7079cd4c632e15965681f8

FIX: fix the spelling of bug in labels

---

.github/workflows/build_ubuntu.yml

ref: https://github.com/bambulab/BambuStudio/pull/1968#issuecomment-1633718747

added commands to free up space before building

---

.github/workflows/build_ubuntu.yml

current the name are the same
just add some string to different them
Change-Id: Ie90c0595a1240e7739a7fc0b0c45f0db1341314b

ENH: linux: set the two buildings to different names

---

bbl/i18n/cs/BambuStudio_cs.po

Please include the Czech language in BambuStudio.
I am the author of the already published Czech version of OrcaSlicer.
After several requests from BambuStudio users, I translated this software. In the attachment, I am also sending the translated web interface Text.json file.
Thank you in advance for your reply
Best regards, Mošner
[text cs_CZ.zip](https://github.com/bambulab/BambuStudio/files/12475139/text.cs_CZ.zip)

BambuStudio translation into Czech cs_CZ

---

bbl/i18n/uk/BambuStudio_uk.po

This Pull Request introduces updates for the Ukrainian translation. We've made various improvements and corrections to enhance the overall quality and consistency of the Ukrainian localization.
Here's a summary of the key changes made in this update:
- Corrected spelling and grammatical errors in various UI elements.
- Ensured consistent terminology usage throughout the application.
- Updated translations for new features and user interface elements added since the last translation update.
- Improved clarity and readability of translated content.
- Addressed user feedback and suggestions related to the Ukrainian localization.
We would like to express our gratitude to the contributors who helped make these updates possible:
- @iZonex
To ensure the quality of the Ukrainian localization, …

Ukrainian Translation Updates 1.8.0 Public beta 2

---

src/libslic3r/ArcFitter.cpp
src/libslic3r/Brim.cpp
src/libslic3r/BuildVolume.cpp
src/libslic3r/Config.cpp
src/libslic3r/FaceDetector.cpp
src/libslic3r/Format/STEP.cpp
src/libslic3r/Format/bbs_3mf.cpp
src/libslic3r/Layer.hpp
src/libslic3r/ObjectID.hpp
src/libslic3r/Preset.hpp
src/libslic3r/Utils.hpp

Using `gcc version 13.2.0 (GCC)` in a Flatpak sandbox, I ran into a number of problems.
This isn't all the problems I've run into, but this is all the ones I can fix right now.

Fix a number of compilation problems

---

deps/OpenEXR/OpenEXR.cmake

caused by previous gcc patch from linux
github: https://github.com/bambulab/BambuStudio/issues/3064
Change-Id: If6075068b961b956fc2e0ca369adc01b2f50b0db

FIX: deps: fix the compiling issue under windows

---

deps/CMakeLists.txt
deps/OpenCV/OpenCV.cmake

jira: none
Change-Id: I1ae4a2bd5618e9e620b08a937904d6af5d00bc41

NEW:add OpenCV.cmake in deps

---

bbl/i18n/uk/BambuStudio_uk.po

This Pull Request introduces updates for the Ukrainian translation. We've made various improvements and corrections to enhance the overall quality and consistency of the Ukrainian localization.
Here's a summary of the key changes made in this update:
- Corrected spelling and grammatical errors in various UI elements.
- Ensured consistent terminology usage throughout the application.
- Updated translations for new features and user interface elements added since the last translation update.
- Improved clarity and readability of translated content.
- Addressed user feedback and suggestions related to the Ukrainian localization.
We would like to express our gratitude to the contributors who helped make these updates possible:
- @iZonex
To ensure the quality of the Ukrainian localization, …

LANG: Ukrainian Translation Updates for 1.9.1 Beta 4

---

bbl/i18n/fr/BambuStudio_fr.po

Add some french translation to help

Add french translation

---

bbl/i18n/ja/BambuStudio_ja.po

Randomly translated English displays that caught my eye into Japanese.
I apologize if this first commit doesn't adhere to the conventional expressions used in Bambu Studio or 3D printing.

ja .po file contribution

---

version.inc

Change-Id: I0d57250042fe202a7e90f478bfc801d7bd8a65ee

ENH: version: bumped to 1.9.3

---

README.md

Change-Id: Idfed4ec9d024d0e2cf8dd8fee01c508940b385ed

ENH: readme: add back the logo

---

README.md

Change-Id: I2de515fe3d71cfe6b7ddf2c1b52f25c03f77ea2b

ENH: remove some text

---

src/libslic3r/GCode.cpp

jira:NONE
Change-Id: I833c2e84ba58919de5eb8f20c7f93919b180dadc

FIX: remove white space in line end

---

bbl/i18n/uk/BambuStudio_uk.po

This Pull Request introduces updates for the Ukrainian translation. We've made various improvements and corrections to enhance the overall quality and consistency of the Ukrainian localization.
Here's a summary of the key changes made in this update:
- Corrected spelling and grammatical errors in various UI elements.
- Ensured consistent terminology usage throughout the application.
- Updated translations for new features and user interface elements added since the last translation update.
- Improved clarity and readability of translated content.
- Addressed user feedback and suggestions related to the Ukrainian localization.
We would like to express our gratitude to the contributors who helped make these updates possible:
- @iZonex
To ensure the quality of the Ukrainian localization, …

LANG: Ukrainian Translation Updates for 1.9.7.52

---

src/slic3r/GUI/CreatePresetsDialog.cpp

Add LDO as a filament vendor

---

src/slic3r/GUI/CreatePresetsDialog.cpp

Add filament_vendors：FusRock

---

README.md

Change-Id: I5d5fc8f18801754a8823bcfd3bfb9d021ad208e1

ENH: remove redundant space in readme

---

version.inc

Change-Id: I98ff7c55c3fff2380665360acc8a9c2a4e419a47

ci: update build version to 02.00.03.53

---

.github/workflows/build_all.yml
.github/workflows/build_bambu.yml
.github/workflows/build_deps.yml
deps/TIFF/TIFF.cmake

jira: nojia
Change-Id: Ifa79d713cb09ca927797160c7fbb53f266501f84 (cherry picked from commit b059336940dd038b30e1cf0a44ebcd33df771a8c)

FIX:github workflow fix

---

src/slic3r/GUI/MediaPlayCtrl.cpp

Fix typo operating to operation.

Fix typo operating to operation

---

src/slic3r/GUI/CalibrationWizardPresetPage.cpp
src/slic3r/GUI/Plater.cpp
src/slic3r/GUI/Plater.hpp
src/slic3r/Utils/CalibUtils.cpp

github: 7543
Change-Id: Ifa20d786836f1991af35b3b95e25f91431d752e0

sync codes to 02.02.00.68 part2

---

src/libslic3r/FuzzySkin.cpp
src/libslic3r/Geometry/VoronoiUtilsCgal.cpp
src/slic3r/GUI/DeviceErrorDialog.hpp
src/slic3r/GUI/EncodedFilament.hpp
src/slic3r/GUI/Jobs/EmbossJob.cpp
src/slic3r/GUI/PartSkipDialog.cpp
src/slic3r/GUI/Plater.cpp
src/slic3r/GUI/SkipPartCanvas.cpp
src/slic3r/GUI/Widgets/LinkLabel.cpp
src/slic3r/GUI/Widgets/LinkLabel.hpp

As used in https://github.com/flathub/com.bambulab.BambuStudio/pull/64

2.2.0 Beta 2 build fixes

---

src/libslic3r/GCode.cpp
src/slic3r/GUI/CalibrationWizard.cpp

jira: STUDIO-14212
Change-Id: I6123b51987451f0281dad383ec0ea85f8bc1243c

FIX: crash when cali

---

version.inc

Change-Id: I946c97416e4d6e34cfd97e9496f99a3346581a92

ci: update build version to 02.02.01.60
