- src/BambuStudio_app_msvc.cpp
Removing check for local or Remote FX virtualized RDP session. The checks below this line already verify if proper OpenGL support is present.
> Fixes #740

- src/platform/unix/BuildLinuxImage.sh.in
Removing some workarounds that are no longer necessary.
Ref: #12
> BuildLinuxImage.sh: Remove workarounds that are no longer needed

- deps/wxWidgets/wxWidgets.cmake
Each time the dependency build was run, previously, the build system attempted to patch wxWidgets after checking it out from Git.  The problem, of course, is that if this happened once, it would not succeed a second time, so the only workaround was to blow away the wxWidgets source tree.
The real solution to this is to create a BBL fork of wxWidgets (or to upstream the changes...).  But for now, we add a file to determine whether the patch has taken place already, and if it's there, we don't apply the patch again.  This will mean that all kinds of exciting things happen if you change Git revisions of wxWidgets or the patch changes (in those cases, you'll have to blow away the build), but at least this makes it possible to build twice in the same repository in the best case.
To update an …
> deps/wxWidgets: avoid patching too many times

- src/BambuStudio.cpp
- src/slic3r/CMakeLists.txt
- src/slic3r/GUI/MediaPlayCtrl.cpp
- src/slic3r/GUI/Notebook.cpp
- src/slic3r/GUI/Printer/BambuTunnel.h
- src/slic3r/GUI/Printer/PrinterFileSystem.cpp
- src/slic3r/GUI/Printer/gstbambusrc.c
- src/slic3r/GUI/Printer/gstbambusrc.h
- src/slic3r/GUI/wxMediaCtrl2.cpp
- src/slic3r/pchheader.hpp
This PR adds Linux support for the X1's live video camera.
wxWidgets on Linux uses GStreamer as its back-end for wxMediaCtrl, which doesn't have a bambu: URI handler.  On Windows, this is handled by a Windows Media subsystem plugin, and on Mac, this is handled with a BambuPlayer class.  Luckily, the libBambuSource.so binary that is distributed with the network plugin package already contains support for receiving h.264 data from the network, and the API is the same as is used by the tiny bambusource.exe binary on Windows; we glue this into a GStreamer source plugin that registers a URI handler for bambu:.
To make this work, we make a few additional changes elsewhere.  GStreamer seems to have trouble rendering an Xv overlay onto a 32bpp X visual, but Bambu Slicer seems to request a 32bpp …
> Add support for Bambu Lab X1 series live video stream on Linux

- src/slic3r/GUI/MediaPlayCtrl.cpp
On Linux, there are actually two ways to build a wxWidgets video player -- Gstreamer, and gstreamer-player.  (I have no idea why they did not just pick one.)  The gstreamer-player path is a little different, and did not reliably start the stream previously.  (The symptom is that when built on a system that has the `libgstreamer-plugins-bad1.0-dev` package installed, the video player would stay black and would say "Loading..." forever, but if you right-clicked on the play button, it would in fact start playing.)  This collection of hacks gets gstreamer-player working.
> Linux: MediaPlayCtrl: make playback more reliable with wxUSE_GSTREAMER_PLAYER for systems that have that

- src/slic3r/GUI/Plater.cpp
Steps to reproduce:
1. Load a model with Unicode characters in its path:  `c:\xxx\中文路径\a.stl`
2. Slice it and click the `Print` button
3. Application clashes.
-SoftFever
> Fix a crashing issue when the model's path has Unicode characters on third party printers.

- src/libslic3r/TreeSupport.cpp
- src/slic3r/GUI/3DScene.hpp
- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GLCanvas3D.hpp
- src/slic3r/GUI/GUI_App.cpp
- src/slic3r/GUI/ImGuiWrapper.cpp
- src/slic3r/GUI/ImGuiWrapper.hpp
Some modern compilers, including GCC, Clang, and MSVC, support a mode called "address sanitizer" ("asan"), invoked with `-fsanitize=address`, which adds extra tracking around all memory accesses.  Compiling Bambu Studio with asan turned on revealed a handful of memory usage errors; some of them are not critical, but some of them do seem quite important and could result in stability issues on any platform, not just Linux.
While I was in here, I also tracked down the crash associated with Linux background startup, and I *think* I fixed it.  It's very difficult to reproduce, though, so it's hard to know for sure.
> Address Sanitizer stability and correctness cleanups

- .github/workflows/build_linux.yml
- BuildLinux.sh
- src/platform/unix/build_appimage.sh.in
I have created a PR to create AppImages using GitHub Actions Workflow. 
The main modification I made was add a flag to BuildLinux.sh so it'll skip the memory check as it's not a problem to compile with less ram. That ram check could be removed but I've just simply added a flag to skip it. 
I also added a check to see if you are attempting to run the AppImage build in a docker container so it'll patch the appimagetool so it'll run and use the extract and run option in that scenario. GH Action workflow isn't in a container but when testing with [nektos/act](https://github.com/nektos/act) it was needed to confirm the build was working correctly. 
I've incorporated @zhaofengli 's fix  [Disable EGL for wxGLCanvas](https://github.com/zhaofengli/BambuStudio/tree/wx-no-egl) with my PR to get the …
> AppImage builder feature

- DockerRun.sh
In some X installations using the MIT shared memory extension for rendering window elements, Bambu
Studio needs direct access to a UNIX socket
for fast rendering.
This fix passes `--ipc host` with docker run
to allow the container to just have direct access
to the host's IPC system.
The error message that this solves is:
```
(bambu-studio:1): Gdk-ERROR **: 00:02:37.498: The program 'bambu-studio' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 316 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the …
```
> Docker Run Fix for MIT-SHM BadAccess X socket permissions

- Dockerfile
These two packages are needed to stream video from the webcam
> Docker Run:  Add gstreamer plugins for video support

- deps/OpenEXR/0001-OpenEXR-GCC13.patch
- deps/OpenEXR/OpenEXR.cmake
- deps/TBB/0001-TBB-GCC13.patch
- deps/TBB/TBB.cmake
- src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h
- src/clipper2/Clipper2Lib/src/clipper.engine.cpp
Arch and Fedora switched to GCC 13.x as default making it impossible to build BambuStudio on those distros.
Only minor cleanup was required to fix that.
> Fix building with GCC13 (required to build on Arch and Fedora)

- src/slic3r/GUI/GUI_App.cpp
This fixes a crash similar to <https://github.com/prusa3d/PrusaSlicer/issues/8299>.
> Initialize locale before wxTranslations::Get()

- src/mcut/include/mcut/internal/hmesh.h
GCC 13 requires an explicit #include <cstdint> for the std::uint32_t  data type used by this file. Adding this include allows for the whole project to successfully be compiled on GCC 13
> Fix mcut for GCC 13

- README.md
- Readme.txt
The README still denied the existence of the Linux build. This [confused people](https://www.reddit.com/r/BambuLab/comments/14gjq6k/on_the_github_no_linux_support_guess_i_didnt_read/).
> Mention Linux version in README

- .github/workflows/build_ubuntu.yml
- Containerfile
added a copy of the job to build with ubuntu 20.04 builder image to define correct glib versions. Also see discussion in https://github.com/bambulab/BambuStudio/issues/1667
> additional appimage job for ubuntu 20.04

- deps/GMP/GMP.cmake
download GMP from github directly for gmp blocking the access from github
Change-Id: I344f14dded450c5a7549b2a94cafe46c25db9448
> ENH: deps: fix the compiling issue caused by gmp downloading fail

- doc/How to build - Mac OS.md
While trying to compile on my Macbook Pro running Ventura 13.4.1 using AppleClang 14.0.3.14030022, I ran into an error related to bad syntax `&& && git init` and was unable to finish compiling.
I was able to determine that the changes made in #1097 caused this issue. With the fix in this PR, I was able to successfully finish compiling.
I also noticed that the compile guide was missing a `make` command for arm64 architecture and have added that.
Lastly, I made some adjustments to the formatting in the Mac Compile Guide to try and improve readability.
> Update MacOS compile guide

- .github/ISSUE_TEMPLATE/bug_report.yml
This fixes a few issues with the template I noticed while filing a bug:
* Wrong home directory for MacOS and Linux
* Missing endquote after Linux directory leading to broken formatting
* Reference to … Cura?
* Inconsistent spacing
> Fix bug template

- bbl/i18n/BambuStudio.pot
- bbl/i18n/de/BambuStudio_de.po
- bbl/i18n/en/BambuStudio_en.po
- bbl/i18n/es/BambuStudio_es.po
- bbl/i18n/fr/BambuStudio_fr.po
- bbl/i18n/hu/BambuStudio_hu.po
- bbl/i18n/it/BambuStudio_it.po
- bbl/i18n/ja/BambuStudio_ja.po
- bbl/i18n/ko/BambuStudio_ko.po
- bbl/i18n/nl/BambuStudio_nl.po
- bbl/i18n/sv/BambuStudio_sv.po
- bbl/i18n/zh_cn/BambuStudio_zh_CN.po
- src/slic3r/GUI/CalibrationWizard.cpp
- src/slic3r/GUI/CalibrationWizardSavePage.cpp
Change "droped" to dropped for flow rate calibration fail.
Discovered this typo during my flow rate calibration for my X1C
> Fix typo during flow rate calibration failure

- src/libslic3r/CMakeLists.txt
- src/libslic3r/Format/ModelIO.hpp
- src/libslic3r/Format/ModelIO.mm
- src/libslic3r/Model.cpp
- src/slic3r/GUI/GUI_App.cpp
This PR adds support for a range of 3D flle formats for import, making use of [ModelIO](https://developer.apple.com/documentation/modelio) on macOS:
This is a version of my [PR to PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/pull/11029) that has been refactored for BambuStudio 
* [Universal Scene Description](https://openusd.org/release/index.html)
* [Alembic](https://www.alembic.io)
* [PLY](https://en.wikipedia.org/wiki/PLY_(file_format)#:~:text=PLY%20is%20a%20computer%20file,list%20of%20nominally%20flat%20polygons.)
This change only affects macOS users, and since it uses a system framework, it introduces no extra library dependencies. ModelIO is supported since macOS 10.11 which matches the [minimum system requirements](https://help.prusa3d.com/article/minimum-system-requirements_ …
> Add ModelIO support on macOS

- src/libslic3r/Print.cpp
As it were, 1 mm would be disallowed but 0.99 would be allowed for 0.4 nozzle.  1 mm is the sane maximum and 0.99 is unnecessary tedious to write.
OrcaSlicer already has this as `>` (it also allows 5x nozzle size but I personally see no use for that considering the nozzle flat size of Bambu hotends).
> Allow line width of nozzle diameter * 2.5

- cmake/modules/MacOSXBundleInfo.plist.in
- src/platform/osx/Info.plist.in
This pull request introduces updates to the paths of `.icns` files in our macOS application. These changes are necessary to accommodate a new directory structure, where icons will now be stored in the `images` subfolder within the `Resources` directory.
- The changes affect two key files:
1. src/platform/osx/Info.plist.in
2. cmake/modules/MacOSXBundleInfo.plist.in
- In all lines where the path to `.icns` icon files was used, the path has been updated to reflect the new directory structure.
- For example, lines like `<string>BambuStudio.icns</string>` have been changed to `<string>images/BambuStudio.icns</string>` in `Info.plist`.
- These modifications apply to all references to `.icns` files in the specified files.
- Icons didn’t work with associated files in MacOS
- Following the …
> Fix .icns File Paths for Directory Structure in macOS

- src/libslic3r/PrintConfig.cpp
Super minor fix. Same typo is in the Bambu (X1/C at least) firmware as well, but I do not see that as open source.
> Update PrintConfig.cpp to fix typo

- src/slic3r/GUI/PhysicalPrinterDialog.cpp
Make initializers explicit to avoid ambiguous wxArrayString overloads.
```
src/slic3r/GUI/PhysicalPrinterDialog.cpp: In member function ‘void Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(Slic3r::GUI::ConfigOptionsGroup*)’: src/slic3r/GUI/PhysicalPrinterDialog.cpp:332: error: call of overloaded ‘set_values(<brace-enclosed initializer list>)’ is ambiguous
332 |         choice->set_values({ m_config->opt_string("printhost_port") });
|
```
See https://github.com/prusa3d/PrusaSlicer/pull/11769
> FIX: Fix build error with wxWidgets 3.2.4

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/ImGuiWrapper.cpp
On Windows, if your display scaling is greater than 300%, the text rendered by imgui will be garbled. Allowing imgui to do the scaling instead of making the font to large corrects the issue.
This fixes #2626
> Fix garbled text when display scalling > 300%

- deps/Boost/Boost.cmake
the original url can not be used
create a new one on bambulab
Change-Id: Ie8c1fc52c717307a2a7f8475f5686b6a231002af
> FIX: Boost: fix the building error on github workflow

- src/platform/unix/BambuStudio.desktop
Make the "Open in BambuStudio" button on MakerWorld works by informing the system that BambuStudio is the application to handle URLs with the bambustudio scheme, and that it can handle URLs, not just local files.
This fixes this error message visible in Firefox' console when clicking the button on the website:
```
Prevented navigation to “bambustudio://open?file=https%3A%2F%2Fmakerworld.bblmw.com[...]bambu_scraper_grip_ams.3mf” due to an unknown protocol.
```
> unix: Fix "Open in BambuStudio" button on MakerWorld

- version.inc
The value of BBL_INTERNAL_TESTING is reversed and should be set to 1 when requested instead of 1 when not requested.
Fixes: 79480405a022 ("ENH: update version to 1.3.0")
Note: pretty sure I got this right, in my testing, without `-DBBL_RELEASE_TO_PUBLIC=1` in the build flags, it would default to an "internal testing" version instead of a "beta version".
> Fix "Beta Version" appearing as "Internal Version"

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
This PR introduces changes to the logic used for calculating and displaying the estimated printing time in our printing software. It specifically adds a conditional check to distinguish between BBL and non-BBL printers, affecting how the estimated printing time is displayed.
1. **Conditional Check for BBL Printers**: Implemented a check to determine if the printer is a BBL printer using `if (!print.is_BBL_Printer())`. This allows for different handling of estimated printing times based on the printer type.
2. **Separate Handling for Estimated Printing Time**:
- For non-BBL printers, the code now includes the estimated printing time in a specific mode (normal constant).
- For BBL printers, the estimated printing time is replaced with the model printing time and total estimated time.
This …
> Update Estimated Printing Time Logic

- src/slic3r/GUI/GUI_Factories.cpp
Show the actual filament labels in the "Change Filament" context menu instead of "Filament 1", "Filament 2", etc.
This makes it much quicker to tell what filament is being selected, especially when utilizing the "sync from AMS" button with a printer with several AMS units attached.
> Display filament labels in "change filament" context menus

- CMakeLists.txt
This PR removes some redundant code in the CMakeLists for Linux compilation.  The code removed implements a workaround for older versions of CMake that did not support `CMAKE_CXX_STANDARD`; however, the very first line in the CMakeLists requires a version of CMake newer than the version that implemented the worked-around feature.  Therefore, the `if` clause will never be true!
> Remove redundant CMakeLists code for Linux

- src/slic3r/GUI/Jobs/PrintJob.cpp
```
/run/build/BambuStudio/src/slic3r/GUI/Jobs/PrintJob.cpp: In member function ‘virtual void Slic3r::GUI::PrintJob::process()’: /run/build/BambuStudio/src/slic3r/GUI/Jobs/PrintJob.cpp:291:22: error: ‘regex’ is not a member of ‘std’; did you mean ‘boost::regex’?
291 |                 std::regex pattern("_+");
|                      ^~~~~
```
> slic3r: Fix std::regex declaration

- deps/OpenCV/OpenCV.cmake
This is a port of https://github.com/SoftFever/OrcaSlicer/pull/5311 which is a fix for https://github.com/SoftFever/OrcaSlicer/issues/5194 which happens to apply to Bambu Studio as well
> Disable use of system eigen3 for OpenCV.cmake

- src/slic3r/GUI/KBShortcutsDialog.cpp
- src/slic3r/GUI/MainFrame.cpp
This is for issue #4055.
The problem is that hitting "Cmd-Shift-M" on mac always minimizes the app, even though it should only minimize on "Cmd-M", and not on "Cmd-Shift-M".  This means that on the "Prepare" and "Preview" screens on a Mac, it is impossible to get the 3DConnexion preferences dialog to appear.
The code that minimizes (using the WXWidgets "Iconize()" call) happens in MainFrame.cpp keyboard event loop.  The code that's checking, looks for "Cmd-M" but does not check for any other keyboard modifiers, so I added a check to ignore the event if Shift is pressed along with "Cmd-M".
There's a secondary issue that isn't really relevant to this bug in that the app will still minimize when pressing "Cmd-Shift-M", but ONLY on the "Home" sub-screen. (all other sub-screens work as they …
> Prevent Cmd-Shift-M from minimizing on  EXCEPT on "Home" sub-screen, thus preventing 3DConnexion prefs dialog from working

- src/clipper2/CMakeLists.txt
- src/libslic3r/CMakeLists.txt
Bambu studio currently fails to build on Fedora 40. This is because the CMake configuration of `libslic3r` and `libslic3r_cgal` currently does not explicitly specify the C++ standard, but it seems like the `libslic3r` and `libslic3r_cgal` code assumes C++17. Without explicit specification, the compiler uses C++20.
Also added `-Wno-error=template-id-cdtor` to the compiler flags for `Clipper2`, preventing this warning from being thrown as an error. The `template-id-cdtor` warning being thrown as an error is a [c++20 addition in gcc](https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gcc/C_002b_002b-Dialect-Options.html#index-Wno-template-id-cdtor).
This fixes #4018.
> Explicitly specify C++17 in libslic3r and libslic3r_cgal cmake, fixing build on Fedora 40

- resources/profiles/Qidi/filament/Generic ABS @Qidi.json
- resources/profiles/Qidi/filament/Generic ASA @Qidi.json
- resources/profiles/Qidi/filament/Generic PA @Qidi.json
- resources/profiles/Qidi/filament/Generic PA-CF @Qidi.json
- resources/profiles/Qidi/filament/Generic PC @Qidi.json
- resources/profiles/Qidi/filament/Generic PETG @Qidi.json
- resources/profiles/Qidi/filament/Generic PETG-CF @Qidi.json
- resources/profiles/Qidi/filament/Generic PLA @Qidi.json
- resources/profiles/Qidi/filament/Generic PLA Silk @Qidi.json
- resources/profiles/Qidi/filament/Generic PLA-CF @Qidi.json
- resources/profiles/Qidi/filament/Generic PVA @Qidi.json
- resources/profiles/Qidi/filament/Generic TPU @Qidi.json
- resources/profiles/Qidi/filament/QIDI ABS-GF25 @Qidi Q1 Pro 0.4 nozzle.json
- resources/profiles/Qidi/process/0.18mm Standard @Qidi Q1 Pro 0.6 nozzle.json
Jira: 7761
Signed-off-by: qing.zhang <qing.zhang@bambulab.com>
Change-Id: I017b56eab699b103628ecb80452d9a4a5ea0ae88 (cherry picked from commit 05ddfbec848ee0b7becb7039873edc62c8e650ad)
> FIX: duplicate setting id and error vendor

- DockerRun.sh
When using `DockerRun.sh` stale containers were left over after closing the application. These containers would also not be re-used.
Add the `--rm` flag to make Docker delete the containers after running the application, since they are re-created for each run anyways.
> Add Docker flag to remove containers after finishing

- src/libslic3r/GCode.cpp
- src/libslic3r/GCode/GCodeProcessor.cpp
- src/libslic3r/GCode/GCodeProcessor.hpp
This is the successor of https://github.com/bambulab/BambuStudio/pull/4611, which was just another workaround after detailed analysis.
As outlined in the original PR, BambuStudio will not use a spiral Z hop for layer changes when timelapse is disabled and there is no infill. Actually, it will not use a spiral Z hop in other scenarios too (whenever timelapse gcode is injected), but they don't matter as much as the layer changes.
- Find a slow-motion video here: [imgur](https://imgur.com/a/1P2z3HZ)
- Find a .3mf / gcode file here: [missing_spiral_z.zip](https://github.com/user-attachments/files/16603440/missing_spiral_z.zip)
**Screenshot show the model's missing spiral Z hop:**
**Screenshot after successful fixing of the bug (see "Solution/PR Content"):**
Timelapse gcode is injected into …
> Bugfix: support spiral lift Z hop without timelapse enabled (fix stringing)

- src/libslic3r/Support/SupportParameters.hpp
```
/run/build/BambuStudio/src/libslic3r/Support/SupportParameters.hpp: In constructor ‘Slic3r::SupportParameters::SupportParameters(const Slic3r::PrintObject&)’: /run/build/BambuStudio/src/libslic3r/Support/SupportParameters.hpp:172:39: error: ‘warning’ was not declared in this scope
172 |                     BOOST_LOG_TRIVIAL(warning) << "tree support default to organic support";
|                                       ^~~~~~~
/run/build/BambuStudio/src/libslic3r/Support/SupportParameters.hpp:172:21: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
172 |                     BOOST_LOG_TRIVIAL(warning) << "tree support default to organic support";
|                     ^~~~~~~~~~~~~~~~~
/run/build/BambuStudio/src/libslic3r/Support/SupportParameters.hpp:175:39: error: ‘warning’ …
```
> libslic3r: Fix BOOST_LOG_TRIVIAL declaration

- linux.d/debian
The `test(1)` command (also known as `[(1)`) does not use the `==` syntax for testing equality, which is a feature of bash's `[[` builtin. String equality is tested with '=', and numeric equality with `-eq`. This eliminates a series of warnings when running `BuildLinux.sh` on Debian-derived systems:
```
[schwarzgerat](0) $ ./BuildLinux.sh -u
./linux.d/debian: line 39: [: ==: unary operator expected
./linux.d/debian: line 39: [: ==: unary operator expected
./linux.d/debian: line 42: [: ==: unary operator expected
```
> linux.d/debian: use correct string match syntax

- src/slic3r/GUI/DeviceManager.cpp
```
/run/build/BambuStudio/src/slic3r/GUI/DeviceManager.cpp: In static member function ‘static boost::bimaps::bimap<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > Slic3r::DeviceManager::get_all_model_id_with_name()’: /run/build/BambuStudio/src/slic3r/GUI/DeviceManager.cpp:6076:5: error: ‘wxDir’ was not declared in this scope; did you mean ‘wxDIR’?
6076 |     wxDir dir(Slic3r::resources_dir() + "/printers/");
|     ^~~~~
|     wxDIR
```
> slic3r: Fix wxDir declaration

- src/libslic3r/PrintConfig.cpp
This change fixes a typo in the tooltip on "Role base wipe speed".
> Fix typo: wip action -> wipe action

- resources/profiles/Elegoo/filament/Generic ABS @Elegoo.json
- resources/profiles/Elegoo/filament/Generic PETG @Elegoo.json
- resources/profiles/Elegoo/filament/Generic PLA @Elegoo.json
When using the Neptune 4 Plus on the 1.10 beta all the Elegoo filaments are missing and we are left with a generic filament. This PR adds all the Neptune 4 family of printers as supported by the generic Elegoo filaments.
> Add all Neptune 4 printers as supported by Elegoo generic filaments

- src/libslic3r/PrintConfig.cpp
See below screenshot. When hover cursor on the Cool Plate (not supertack)'s initial layer print temp setting, the tooltip is showing "Bambo Cool Plate Supertack" which is incorrect.
This PR fixes this tooltip verbiage.
> Fixed tooltip for cool plate initial layer temp.

- src/slic3r/GUI/Mouse3DController.cpp
Update the device list to match the upstream spacenavd one.
> Mouse3DController: Add SpaceMouse Wireless BT support

- src/slic3r/GUI/UnsavedChangesDialog.cpp
Some fonts are illegible in light theme on Linux:
The foreground color `wxSystemSettings::GetColour(wxSYS_COLOUR_INFOTEXT)` varies on different platform while the background color is hard coded, which causes the problem. Just hard code the foreground color to fix it.
After the fix:
> Fix illegible color in 'unsaved changes dialog' on Linux

- bbl/i18n/en/BambuStudio_en.po
Capatizle `Enable` in `Enable multi instance rendering by OpenGL`, so it matches the rest of the text.
> Tiny English translation update

- src/CMakeLists.txt
Similar to what is done to support zh_CN, but for pt_BR.
Fixes #5580
> i18n: added special case for pt_BR folder naming on Unix

- BuildLinux.sh
This changes the way the Linux build script recognizes which distribution script might be compatible with the host OS.  It does so by checking both the `ID` and `ID_LIKE` tags in `/etc/os-release` against available scripts in `linux.d`.  First match is used.
Note that ID_LIKE isn't a 100% compatability guarantee, but it gives the user a fighting chance that the script will work for their distribution, and should reduce the need for manual addition of more distribution targets.
> Change Linux build script to recognize more supported distributions

- src/slic3r/GUI/GUI_App.cpp
This patch attempts to keep the printer access code from being cleared erroneously on a lost or failed connection.  This only applies to LAN mode.
Notes:
- The setting is 'access_code'.  There is also a setting named 'user_access_code', but it's function is unclear and may be vestigal.
- Some parts of the network connection behavior are handled by the networking plugin.  I can't seem to make the machine list refresh from outside.
> Quick fix attempt for machine password erased on disconnect (issue #4076).

- src/slic3r/GUI/Widgets/PopupWindow.cpp
- src/slic3r/GUI/Widgets/PopupWindow.hpp
Fixes https://github.com/bambulab/BambuStudio/issues/4201 that makes Bambu Studio unusable under some window managers, but reintroduces inconvenience of PopupWindow remaining in front after alt+tab.
> Fix PopupWindow dropdown menus do not display #4201 

- deps/OCCT/0001-OCCT-fix.patch
Pick up build error fix from upstream:
https://github.com/Open-Cascade-SAS/OCCT/commit/7236e83dcc1e7284e66dc61e612154617ef715d6
```
/run/build/BambuStudio/deps/build/dep_OCCT-prefix/src/dep_OCCT/src/StdPrs/StdPrs_BRepFont.cxx: In member function ‘Standard_Boolean StdPrs_BRepFont::renderGlyph(Standard_Utf32Char, TopoDS_Shape&)’: /run/build/BambuStudio/deps/build/dep_OCCT-prefix/src/dep_OCCT/src/StdPrs/StdPrs_BRepFont.cxx:465:30: error: invalid conversion from ‘unsigned char*’ to ‘const char*’ [-fpermissive]
465 |     const char* aTags      = &anOutline->tags[aStartIndex];
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                              |
|                              unsigned char*
```
> FIX: occt build failure

- src/slic3r/GUI/MainFrame.cpp
- src/slic3r/GUI/StatusPanel.cpp
At every filament related event, the old code would try to set the keyboard focus to the "Device" tab, leading to a number of, either, focus stealing events, or notifications if the desktop has focus stealing prevention (like GNOME).
Disable the focus setting on Linux to prevent that focus stealing.
Closes: https://github.com/bambulab/BambuStudio/issues/3046
> FIX: Fix focus stealing from app when filament changes

- src/libslic3r/Clipper2Utils.hpp
- src/libslic3r/ExPolygon.cpp
- src/libslic3r/ExtrusionEntity.hpp
- src/libslic3r/FilamentGroupUtils.cpp
- src/libslic3r/Fill/FillFloatingConcentric.cpp
- src/libslic3r/Fill/FillRectilinear.cpp
- src/libslic3r/GCode/ToolOrderUtils.hpp
- src/libslic3r/GCode/WipeTower.cpp
- src/libslic3r/GCode/WipeTower.hpp
- src/libslic3r/Interlocking/InterlockingGenerator.cpp
- src/libslic3r/Polygon.cpp
- src/libslic3r/PresetBundle.cpp
- src/libslic3r/PrintConfig.cpp
- src/libslic3r/SVG.cpp
- src/slic3r/GUI/3DScene.hpp
- src/slic3r/GUI/CapsuleButton.cpp
- src/slic3r/GUI/DragDropPanel.hpp
- src/slic3r/GUI/FilamentGroupPopup.hpp
- src/slic3r/GUI/FilamentMapPanel.cpp
- src/slic3r/GUI/ImGuiWrapper.cpp
- src/slic3r/GUI/Widgets/DropDown.cpp
- src/slic3r/GUI/WipeTowerDialog.cpp
- src/slic3r/GUI/WipeTowerDialog.hpp
- src/slic3r/Utils/WxFontUtils.hpp
As needed for the Flatpak build, see https://github.com/flathub/com.bambulab.BambuStudio/pull/56
> Build fixes for 2.0.0

- src/slic3r/GUI/Widgets/FanControl.cpp
The text for "Changed fan speed during printing may affect print quality, please choose carefully." has a typo - "pringing" instead of "printing". 
I simply did a find and replace for all instances of the typo, not sure if more is needed.
> fix: typo "pringing"

- src/slic3r/GUI/GUI_App.cpp
Essentially this PR is a follow up of #5347. It addresses #5347 #6120 #3798
I am not going to talk about the vague "security" approach currently deployed for the URL handler, improve that is out of scope of this PR.
The changes directly implements the decision made by @lanewei120 
> keep the original url judge logic currently, let it go on as before(we will refine more these address check later)
and popup a warning dialog when the url doesn't meet the above
and if user clicks ok, bambu studio will go on to load it
I am currently having issue building on my PC due to strange deps error (W11, every requirement installed, clean clone of repository), so I am using this PR as a github-action build check.
The changes are minimal.
> Allow URL handler to open files from untrusted sites with confirm

- src/libslic3r/GCode.cpp
- src/slic3r/GUI/ConfigManipulation.cpp
- src/slic3r/GUI/Tab.cpp
This functionality is from OrcaSlicer and is used for changing the flow rate of each object on a build plate. 
This functionality is useful to me as to allow for custom flow calibration prints to be performed. Particularly, this allows for the following project on Maker World to work natively on Bambu Studio, without needing Orca Slicer. https://makerworld.com/en/models/189543-improved-flow-ratio-calibration-v3
> Add ability to modify the print flow ratio per object

- src/slic3r/GUI/GLCanvas3D.cpp
- src/slic3r/GUI/GUI_ObjectList.cpp
- src/slic3r/GUI/KBShortcutsDialog.cpp
- add Shift+Command+Z accelerator for redo on macOS
- show the updated shortcut in the keyboard shortcuts dialog
Fixes #3898
> Add macOS ⌘⇧Z redo shortcut

- src/BambuStudio.cpp
A small edge case in the way the glfw/opengl context is handled causes slices performed in environments without opengl, for a multitude of reasons, e.i. wayland, headless etc. to segfault.
The underlying trigger is the fact `shader` is null which causes  `p_opengl_mgr->bind_shader` to crash. I am not too familiar with the overall code architecture, my immediate thought was that in such an environment trying to generate a thumbnail is not really intended, so disabling it entirely would make the most sense. It is also possible to handle the crash more granularity by conditionally calling `bind_shader` based on the current `p_opengl_mgr` and `shader` state.  
In the end this is the smallest change that solves the specific use case we have, gracefully not generating thumbnails while still …
> FIX: Thumbnail generation in CLI mode segfaults when no valid opengl context exists

- src/slic3r/GUI/CreatePresetsDialog.cpp
**Issue**
The CreateFilamentPresetDialog fails to resize properly to show the printer list in the bottom of the dialog window.  This precludes selection of printer(s) which prevents the successful creation of the filament profile.  
**Fix**
This "fix" simple adds the wxRESIZE_BORDER flag on window creation so the dialog can be resized to reveal the printer list.  In my opinion, this is really just a workaround. Ideally the printer list is contained within scrollable control or the is resized window properly when the printer list is populated.
Fixes #7211
> Fixes #7211 where the CreateFilamentPresetDialog fails to resize
